module.exports = [
  'https://www.huggies.com',
  'https://www.Goodnites.com',
  'https://www.Pull-ups.com',
  'https://www.cottonelle.com',
  'https://www.scottbrand.com',
  'https://www.vivatowels.com',
  'https://www.ubykotex.com',
  'https://www.depend.com/',
  'https://www.poise.com/',
  'https://www.kimberly-clark.com',
  'https://www.careers.kimberly-clark.com',
  'https://www.kleenex.com',
  'https://www.huggieshealthcare.com',
  'https://investor.kimberly-clark.com',
]

// [
//   'https://vivaplenitud.com.br',
//   'https://dependstore.co.il',
//   'https://www.intimus.com.br/',
//   'https://www.kimberly-clark.com/',
//   'https://www.viveplenitud.com.ar/',
//   'https://www.poise.com.au/',
//   'https://www.poise.com/en-ca/',
//   'https://www.poise.com/en-us/',
//   'https://www.depend.com.au/',
//   'https://www.depend.com/en-ca/',
//   'https://www.huggies.com.ar/',
//   'https://www.huggies.co.uk/',
//   'https://www.huggies.fr/',
//   'https://www.huggies.com.mx/',
//   'https://www.goodnites.com/en-ca/',
//   'https://www.goodnites.com/en-us/',
//   'https://www.goodnites.com/',
//   'https://www.drynites.com.au/',
//   'https://www.ubykotex.com.au/',
// ]
